name: Build and Deploy

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
 REGISTRY: "cr.selcloud.ru/learn-registry"
 IMAGE_NAME: "learn-image"
 CONTAINER_NAME: "new-container"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login selectl
        run:  docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name:
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --platform linux/amd64 --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME .

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push
    steps:
      - name: Deploy to Selectel cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: REGISTRY,IMAGE_NAME,CONTAINER_NAME,GITHUB_SHA
          script: |
            TAG_NAME=${echo $GITHUB_SHA | head -c7}
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
            docker run -d -p 80:80 --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME
